### ISSUE TITLE
VRCFT not launching after installing the DLL

### ISSUE THREAD

**Issue by VaalkinTheOnly** [200Tigersbloxed/VRCFTOmniceptModule#2]
Sharing this here to potentially help others. I had an issue for a good while with VRCFT not launching after moving the DLL file to the "customlibs" folder

The fix is simple, right click the downloaded DLL and select "properties" (very bottom). Check the "unblock" button at the bottom of the properties tab and save. This should hopefully save you some headache if you're having the same problem.

**Comment by 200Tigersbloxed** [comment]
[This is the issue you're referencing](https://stackoverflow.com/questions/18016315/an-attempt-was-made-to-load-an-assembly-from-a-network-location-which-would-have/27842217#27842217)

This is caused when a newer version of NET Framework is sandboxed in an older version of it. The [latest version](https://github.com/200Tigersbloxed/VRCFTOmniceptModule/releases/latest) should have fixed this, since it uses `net472` now.

**Comment by 200Tigersbloxed** [comment]
[This PR](https://github.com/benaclejames/VRCFaceTracking/pull/102) for VRCFT should automatically unblock the dll before loading, preventing this issue from happening. If pulled, I'll close this issue, as it will have been solved upstream.

**Comment by 200Tigersbloxed** [comment]
Closed as the PR mentioned above has been merged.
